apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-station
  labels:
    app: central-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      containers:
      - name: central-station
        image: central-station
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        volumeMounts:
        - name: parquet-data
          mountPath: /parquet
        - name: bin-data
          mountPath: /app/bin
        - name: hint-data
          mountPath: /app/hint
      volumes:
      - name: parquet-data
        persistentVolumeClaim:
          claimName: parquet-pvc
      - name: bin-data
        persistentVolumeClaim:
          claimName: bin-pvc
      - name: hint-data
        persistentVolumeClaim:
          claimName: hint-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: central-station
spec:
  selector:
    app: central-station
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort